### ISSUE TITLE
TypeError: tuple indices must be integers or slices, not str 

### ISSUE THREAD

**Issue by chookg** [ltdrdata/ComfyUI-extension-tutorials#19]
dwpose-segs-handfix.json 

```
making attention of type 'vanilla-xformers' with 512 in_channels
building MemoryEfficientAttnBlock with 512 in_channels...
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla-xformers' with 512 in_channels
building MemoryEfficientAttnBlock with 512 in_channels...
loading new
Detailer: segment upscale for ((94.401794, 122.9704)) | crop region (473, 614) x 1.2508542193649446 -> (591, 768)
!!! Exception during processing !!!
Traceback (most recent call last):
  File "C:\workspace\ComfyUI_windows_portable\ComfyUI\execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "C:\workspace\ComfyUI_windows_portable\ComfyUI\execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "C:\workspace\ComfyUI_windows_portable\ComfyUI\execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "C:\workspace\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\impact_pack.py", line 1042, in doit
    DetailerForEach.do_detail(image, segs, model, clip, vae, guide_size, guide_size_for, max_size, seed, steps, cfg,
  File "C:\workspace\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\impact_pack.py", line 204, in do_detail
    enhanced_pil, cnet_pil = core.enhance_detail(cropped_image, model, clip, vae, guide_size, guide_size_for_bbox, max_size,
  File "C:\workspace\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\core.py", line 228, in enhance_detail
    positive, cnet_pil = control_net_wrapper.apply(positive, upscaled_image)
  File "C:\workspace\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\core.py", line 1339, in apply
    image = self.preprocessor.apply(image)
  File "C:\workspace\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Inspire-Pack\segs_support.py", line 95, in apply
    return obj.estimate_pose(image, detect_hand, detect_body, detect_face, resolution=resolution)['result'][0]
TypeError: tuple indices must be integers or slices, not str
```

**Comment by ltdrdata** [comment]
You need update `ControlNet Auxiliary Preprocessors`, `ComfyUI Impact Pack`, `ComfyUI Inspire Pack`.

**Comment by chookg** [comment]
> You need update `ControlNet Auxiliary Preprocessors`, `ComfyUI Impact Pack`, `ComfyUI Inspire Pack`.

thanks, buddy. You saved my life. I love you
感谢老铁，666
